SELECT 
  CLASS
  ,(SELECT GRADE FROM COURSE_CREDITS B WHERE A.KOR BETWEEN B.ST_RNG AND B.ET_RNG)||'('||KOR||')' KOR_GRD
  ,(SELECT GRADE FROM COURSE_CREDITS B WHERE A.ENG BETWEEN B.ST_RNG AND B.ET_RNG)||'('||ENG||')'  ENG_GRD
  ,(SELECT GRADE FROM COURSE_CREDITS B WHERE A.MAT BETWEEN B.ST_RNG AND B.ET_RNG)||'('||MAT||')'  MAT_GRD
FROM(
SELECT CLASS,
    ROUND(AVG(KOR),1) KOR
    ,ROUND( AVG(ENG),1) ENG
    ,ROUND( AVG(MAT),1) MAT
    
FROM EXAM_RSLT
WHERE GRADE IN (SELECT ROWNUM FROM DUAL CONNECT BY LEVEL <=3)
GROUP BY CLASS) A;


SELECT CLASS,
    ROUND(AVG(KOR),1) KOR
    ,ROUND( AVG(ENG),1) ENG
    ,ROUND( AVG(MAT),1) MAT
    
FROM EXAM_RSLT GROUP BY CLASS;