SELECT 
MIN(DECODE(W_ID,1,D_ID))일
,MIN(DECODE(W_ID,2,D_ID))월
,MIN(DECODE(W_ID,3,D_ID))화
,MIN(DECODE(W_ID,4,D_ID))수
,MIN(DECODE(W_ID,5,D_ID))목
,MIN(DECODE(W_ID,6,D_ID))금
,MIN(DECODE(W_ID,7,D_ID))토
FROM
(SELECT 

TRUNC(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') WK_ID
,TO_CHAR(TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1,'D') W_ID 
,EXTRACT(DAY FROM TO_DATE(:V_ST,'YYYYMM')+ROWNUM-1) D_ID
FROM DUAL
CONNECT BY LEVEL <=EXTRACT(DAY FROM LAST_DAY(TO_DATE(:V_ST,'YYYYMM')))
)GROUP BY WK_ID
ORDER BY WK_ID;